### ISSUE TITLE
README in Schema folder should also reference sessions table

### ISSUE THREAD

**Issue by talltom** [smart-facility/cognicity-rem-server#26]
Changes to the schema, but from outside the /schema folder by connect-pg-simple.

Perhaps refer back to main readme, where description of connect-pg-simple is provided.
psql mydatabase < node_modules/connect-pg-simple/table.sql

**Comment by matthewberryman** [comment]
The current readme in the schema is specific to passwords in both filename and content, and it makes some sense to have this separate and referenced (since it's mostly code) from the main readme. The main readme already covers how to set up the schema as requested by this enhancement, and I don't see a need to separate out that text—in fact it makes it less obvious to the reader when moved to another file. 

If anything, I would copy the table.sql file from connect-pg-simple over and then document how to run that. I would not do it as a submodule as we don't need the lot and maintaining the single file is as much work as maintaining a submodule reference.

**Comment by benatwork99** [comment]
Yes, on consideration I think I agree that this information belongs in the
main README.

I'm hesitant to copy the SQL from the plugin to our project - while it's
probably OK short-term (the schema shouldn't really change while we're
restricted to backwards-compatible versions via the semver dependency
include), we'd need to remember that if we ever upgraded the plugin we'd
need to upgrade the SQL and it's something that could easily become out of
date.

We could add a new file SESSION-README.md which refers the reader to the
main README for details perhaps? That way if you're in the schema folder
you'll notice it, and it's not something we need to keep up to date.


On 6 June 2016 at 15:22, Matthew Berryman <notifications@github.com> wrote:

> The current readme in the schema is specific to passwords in both filename
> and content, and it makes some sense to have this separate and referenced
> (since it's mostly code) from the main readme. The main readme already
> covers how to set up the schema as requested by this enhancement, and I
> don't see a need to separate out that text—in fact it makes it less obvious
> to the reader when moved to another file.
>
> If anything, I would copy the table.sql file from connect-pg-simple over
> and then document how to run that. I would not do it as a submodule as we
> don't need the lot and maintaining the single file is as much work as
> maintaining a submodule reference.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/smart-facility/cognicity-rem-server/issues/26#issuecomment-223870947>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA7PC9XkG17RpfRJvS-IRu3VtmjkVSSKks5qI66ogaJpZM4IukTV>
> .
>



-- 
-----

Ben Jones
Software Engineer, Selera

p: 02 4223 0003
e: ben.jones@selera.com

**Comment by matthewberryman** [comment]
I don't think we need a separate README in the sql folder to refer back, as users should be reading the main README anyway. Concur regarding copying it over (besides, as per instructions in the main README after installing with npm it should be there anyway under node_modules). Thus I am closing this ticket as I think things are already clear enough.
